apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-volume
  labels:
    app: mysql
spec:
  storageClassName: mysqlstorage #same name with PVC
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: "/mnt/mysqldata"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - centos8
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-volume-claim
spec:
  storageClassName: mysqlstorage #same name with PV
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  selector: 
    matchLabels: 
      app: mysql
