apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-volume
  labels:
    app: wordpress
spec:
  storageClassName: wpstorage
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: "/mnt/wpdata"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - centos8 #name of the Node
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-volume-claim
spec:
  storageClassName: wpstorage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  selector: 
    matchLabels: 
      app: wordpress
